// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9fONvCAACmdKHNVY1sQcU-70zuHWDSSM',
    appId: '1:981205643687:web:de54edc7fd1f524977c682',
    messagingSenderId: '981205643687',
    projectId: 'catatan-kuliah-angelim',
    authDomain: 'catatan-kuliah-angelim.firebaseapp.com',
    databaseURL: 'https://catatan-kuliah-angelim-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catatan-kuliah-angelim.firebasestorage.app',
    measurementId: 'G-8DQKJCJ14Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCfWlu_b7LNHC-YSKpmmXi7LNcxLmMPm4',
    appId: '1:981205643687:android:350f598bab22bc4d77c682',
    messagingSenderId: '981205643687',
    projectId: 'catatan-kuliah-angelim',
    databaseURL: 'https://catatan-kuliah-angelim-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catatan-kuliah-angelim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWKlChe3lZuMbMO0HJVeqWJw1cAX_X7HU',
    appId: '1:981205643687:ios:64be8d06b200816f77c682',
    messagingSenderId: '981205643687',
    projectId: 'catatan-kuliah-angelim',
    databaseURL: 'https://catatan-kuliah-angelim-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catatan-kuliah-angelim.firebasestorage.app',
    iosBundleId: 'com.example.catatanKuliah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWKlChe3lZuMbMO0HJVeqWJw1cAX_X7HU',
    appId: '1:981205643687:ios:64be8d06b200816f77c682',
    messagingSenderId: '981205643687',
    projectId: 'catatan-kuliah-angelim',
    databaseURL: 'https://catatan-kuliah-angelim-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catatan-kuliah-angelim.firebasestorage.app',
    iosBundleId: 'com.example.catatanKuliah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9fONvCAACmdKHNVY1sQcU-70zuHWDSSM',
    appId: '1:981205643687:web:0cce889d6ec12a6677c682',
    messagingSenderId: '981205643687',
    projectId: 'catatan-kuliah-angelim',
    authDomain: 'catatan-kuliah-angelim.firebaseapp.com',
    databaseURL: 'https://catatan-kuliah-angelim-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catatan-kuliah-angelim.firebasestorage.app',
    measurementId: 'G-C40YFLRH8M',
  );
}
